#!/usr/bin/env node

var daemon = require("daemonize2").setup({
    main: "app.js",
    name: "frvr",
    pidfile: "frvr.pid"
});


switch (process.argv[2]) {
  case "start":
    daemon.start().on('stopped',function(err,pid){
      console.log("!!! You may need to check your config !!!");
    })
    break;

  case "stop":
    daemon.stop();
    break;

  case "restart":  
    daemon.stop();
    daemon.start();
    break;    


  case "status" : 
    var pid=daemon.status();
    if (pid==0){
      console.log('not running');
    } else {
      console.log('running ['+pid+']');
    }
    break;   

  default:
    console.log("Usage: [start|stop|restart|status]");
}