#!/usr/bin/env node

var exec = require('child_process').exec, child;

child = exec('export PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin && export NODE_ENV=production && cd /opt/local/lib/node_modules/frvr && node app.js',
  function (error, stdout, stderr) {
    console.log('stdout: ' + stdout);
    console.log('stderr: ' + stderr);
    if (error !== null) {
      console.log('exec error: ' + error);
    }
});